### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by seemsindie** [esnunes/riotjs-loader#10]
When i type this code in script tag:

```
someFunc(e) {
    ...
}
```

I get the following error:

ERROR in ./src/components/header.tag
Module build failed: Error: SyntaxError: unknown: Unexpected token (5:15)
    at Object.module.exports (/home/ivan/Projects/Personal/nut_web/node_modules/riotjs-loader/index.js:37:11)
 @ ./src/pages/home.tag 3:0-35

But this is a valid function in es6 i think...

**Comment by samuelmesq** [comment]
@seemsindie see #11
