### ISSUE TITLE
Does not work with babel 6

### ISSUE THREAD

**Issue by osiloke** [esnunes/riotjs-loader#11]

**Comment by nilpath** [comment]
@osiloke At first, I thought so too. However, I got it working by following the instructions for [compiling with babel 6](http://riotjs.com/guide/compiler/) and then made sure I only use `type="babel"` in my riot tags or to set `{ query: { type: 'babel' } }` on the riotjs-loader in webpack.

**Comment by osiloke** [comment]
cool++
